spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/basquiat?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: basquiat
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      connection-timeout: 10000 # 10 sec.
      maximum-pool-size: 10
      pool-name: basquiat-pool
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        use_sql_comments: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true

server:
  error:
    whitelabel:
      enabled: false
  port: 8088

logging:
  config: classpath:logback-spring.xml